# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0b6708e2296402b1f4ee10c8a899951bac2f6478ed45b898e200fd5d75edaefdcda0622a36765e8486994a9ddb27029a82c1f2f928999c84c091f21889a4262

test:
  secret_key_base: b6c7ee345d3885368b740ea92426c1b2bf7519909041304a8c13ba11bc4de43e5cf318e974ebcd190b2a8a62706ab6f771f16089dfebd4cef694a34217438ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
